[theme]
base = "dark"
primaryColor = "#ef4444"            # accent (red)
backgroundColor = "#0f172a"         # slate-900
secondaryBackgroundColor = "#111827"
textColor = "#e5e7eb"
font = "sans serif"
